@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package melonystudios.stancements.blockentity.custom;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;