@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package melonystudios.stancements.item.custom;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;