@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package melonystudios.stancements.block.custom;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;