@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package melonystudios.stancements.block.custom;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;